version: '3'
services:
  app:
    image: teste_tecnico_digitas:latest
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - mongo-express

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  mongodb-data: